# Pose Estimation with MoveNet Lightning

### Demo:
<img alt="Animation showing pose estimation" src="https://storage.googleapis.com/download.tensorflow.org/example_images/movenet_demo.gif">

### For more info visit following link:
<a href='https://www.tensorflow.org/lite/examples/pose_estimation/overview'>Click Here</a>

### Download MoveNet Lighting model from following link:
<a href='https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/3'>Download Model</a>

## Install Dependencies

Create Virtual Environment & Install Following Dependencies:
- pip install tensorflow
- pip install tensorflow-gpu
- pip install opencv-python

## Import Required Libraries

In [66]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2

## Load Model

In [2]:
interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_lightning_3.tflite')
interpreter.allocate_tensors()

## Draw Keypoints

In [61]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape # frame.shape = (480,640,3)
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, k_conf = kp
        
        if k_conf > confidence_threshold:
            cv2.circle(frame, (int(kx),int(ky)), 4, (255,0,0), -1)

## Draw Connections

In [56]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [70]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape # frame.shape = (480,640,3)
    shaped = np.squeeze(np.multiply(keypoints,[y,x,1]))
    
    for edge,color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):
            cv2.line(frame, (int(x1),int(y1)), (int(x2),int(y2)), (0,255,0), 2)

## Make Detection

In [71]:
# Set Threshold Value in 0-1 range
Threshold_Value = 0.4

# WebCam
cap = cv2.VideoCapture(0)

while cap.isOpened():
    # Read from WebCam by frames
    ret,frame = cap.read()
    
    # Reshape Image - Because MoveNet is accepting input in 192x192x3
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img,axis=0), 192, 192)
    input_image = tf.cast(img, dtype=tf.float32)
    
    
    # Setup Input and Output
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # Make Predictions
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    # Draw Connections
    draw_connections(frame, keypoints_with_scores, EDGES, Threshold_Value)
    
    # Draw Keypoints
    draw_keypoints(frame, keypoints_with_scores, Threshold_Value)
    
    # Show WebCam
    cv2.imshow('MoveNet Lightning', frame)
    
    # Stop the WebCam when 'q' is pressed on the keyboard
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

# Release the WebCam
cap.release()

# Destroy all windows
cv2.destroyAllWindows()

[[[[0.35345793 0.38652807 0.61819375]
   [0.33511513 0.40516967 0.58910155]
   [0.33226004 0.363476   0.5670477 ]
   [0.3578547  0.42342433 0.7167134 ]
   [0.35034204 0.32653317 0.7011305 ]
   [0.49575397 0.45181686 0.6288376 ]
   [0.40715337 0.2542868  0.84890026]
   [0.65517807 0.42161655 0.5363369 ]
   [0.5838014  0.17079657 0.6168313 ]
   [0.8048091  0.42532092 0.4842217 ]
   [0.7449206  0.06227469 0.50324535]
   [0.7979733  0.3771929  0.78881276]
   [0.7792268  0.22587964 0.7374183 ]
   [0.8849466  0.38992774 0.01473314]
   [0.8714174  0.16765885 0.02136683]
   [0.865684   0.35320294 0.05025107]
   [0.86540735 0.34125143 0.02453768]]]]
[[[[0.34044522 0.3916632  0.7183182 ]
   [0.32243907 0.4125756  0.7349712 ]
   [0.31816846 0.3704859  0.75893503]
   [0.34531707 0.43428242 0.5502121 ]
   [0.33673033 0.33360815 0.6162983 ]
   [0.4915346  0.4684146  0.8330146 ]
   [0.3963283  0.25953764 0.83329225]
   [0.6458075  0.4223157  0.586899  ]
   [0.5799236  0.1488902  0.7911366 ]
   [0.792

[[[[0.41224477 0.48072213 0.5774417 ]
   [0.34780347 0.5322092  0.72508395]
   [0.3404308  0.42461497 0.6849966 ]
   [0.30878738 0.5864192  0.48594254]
   [0.2995174  0.34185743 0.8276856 ]
   [0.46364975 0.65673125 0.7897443 ]
   [0.42520154 0.22173163 0.7137933 ]
   [0.8261081  0.75732106 0.66457397]
   [0.81656706 0.14527774 0.60047174]
   [0.86309457 0.7928554  0.05287093]
   [0.89096975 0.12986702 0.04447934]
   [0.78291464 0.511598   0.52270806]
   [0.7801699  0.3026913  0.6613759 ]
   [0.846159   0.55498695 0.05573454]
   [0.84626067 0.211694   0.03307623]
   [0.8441166  0.4743747  0.0379912 ]
   [0.8460827  0.4417153  0.03575486]]]]
[[[[0.4112409  0.48840988 0.7140967 ]
   [0.34615442 0.54383034 0.62525713]
   [0.33671778 0.4333734  0.5290756 ]
   [0.30564633 0.59674144 0.7597243 ]
   [0.2976832  0.34821424 0.62327385]
   [0.45312566 0.6662599  0.8095833 ]
   [0.4175007  0.23048936 0.81455344]
   [0.8156527  0.7570777  0.54291743]
   [0.80385005 0.1550944  0.5432434 ]
   [0.859

[[[[0.40278596 0.45792282 0.5332878 ]
   [0.36161238 0.48922783 0.6042347 ]
   [0.3600915  0.4249228  0.5140148 ]
   [0.36325973 0.50251985 0.51573443]
   [0.36313248 0.3493871  0.6865382 ]
   [0.5086589  0.58968806 0.6332329 ]
   [0.4954456  0.2555555  0.76018727]
   [0.8038484  0.7352001  0.5901421 ]
   [0.7913686  0.18200395 0.482562  ]
   [0.87162125 0.7946929  0.07299417]
   [0.89149845 0.1478673  0.05108842]
   [0.7997161  0.46847546 0.6131681 ]
   [0.7958867  0.28877145 0.5684606 ]
   [0.8487982  0.54220337 0.1872839 ]
   [0.81467026 0.27828062 0.02869168]
   [0.85775983 0.5209756  0.02623722]
   [0.8591136  0.37074992 0.02258438]]]]
[[[[0.35870993 0.40829206 0.7059899 ]
   [0.31656015 0.44392595 0.67769194]
   [0.32384628 0.37579867 0.6297229 ]
   [0.329816   0.49399585 0.6037374 ]
   [0.3367568  0.34516817 0.7201639 ]
   [0.48347482 0.5695922  0.79677415]
   [0.47446916 0.259569   0.7972665 ]
   [0.705856   0.6677964  0.45863947]
   [0.7288797  0.20912579 0.60410523]
   [0.866

[[[[0.32756478 0.387811   0.7083793 ]
   [0.30806005 0.41295862 0.79948324]
   [0.3023162  0.3712076  0.696557  ]
   [0.3283394  0.43825862 0.61281306]
   [0.3137591  0.34000736 0.7265198 ]
   [0.45153922 0.48609254 0.73309106]
   [0.4332528  0.27214003 0.74406564]
   [0.63097507 0.52127606 0.5491302 ]
   [0.59752834 0.21859084 0.61840814]
   [0.81449956 0.53776985 0.606474  ]
   [0.7227267  0.15784147 0.20437211]
   [0.79984564 0.42365453 0.78494614]
   [0.76297235 0.28065196 0.69261736]
   [0.867713   0.4737609  0.01182863]
   [0.7386315  0.20985541 0.33155385]
   [0.86184573 0.38613853 0.02536553]
   [0.86242765 0.2933678  0.03982988]]]]
[[[[0.2928145  0.3711403  0.5526843 ]
   [0.27467805 0.3898263  0.45053855]
   [0.27063593 0.35095584 0.57933784]
   [0.2913599  0.41459447 0.46016353]
   [0.28187275 0.32718113 0.6658153 ]
   [0.42299935 0.47465318 0.79398537]
   [0.41447008 0.23425946 0.8240677 ]
   [0.6117189  0.53367466 0.7417231 ]
   [0.59018326 0.15878573 0.655009  ]
   [0.779

[[[[0.31200323 0.31570128 0.5202989 ]
   [0.23536149 0.3823893  0.6243441 ]
   [0.22035734 0.2671588  0.59683925]
   [0.22007416 0.47506794 0.65704155]
   [0.19268882 0.20839415 0.62493765]
   [0.34872937 0.5546371  0.797162  ]
   [0.37499696 0.09494562 0.76707333]
   [0.74703383 0.59006697 0.59004694]
   [0.71629417 0.07157692 0.03876343]
   [0.8721305  0.625358   0.04560447]
   [0.8585858  0.07632873 0.02669623]
   [0.79865324 0.3847854  0.5096896 ]
   [0.7952246  0.15918753 0.67515594]
   [0.8505106  0.38501775 0.03074703]
   [0.73139304 0.1074128  0.29631627]
   [0.8499378  0.22727636 0.02878022]
   [0.8568951  0.20888919 0.01983309]]]]
[[[[0.31222466 0.31562582 0.48429507]
   [0.23242234 0.38254613 0.65008116]
   [0.21949488 0.2654076  0.5405305 ]
   [0.21632324 0.48226362 0.5634346 ]
   [0.19235192 0.20905766 0.5780355 ]
   [0.34305125 0.55697364 0.6677494 ]
   [0.3732884  0.09372415 0.7318921 ]
   [0.7442629  0.59120303 0.5941559 ]
   [0.7062821  0.03234769 0.0306997 ]
   [0.869

[[[[0.26467776 1.0037935  0.04244283]
   [0.22509561 0.65921056 0.00660101]
   [0.2592921  1.0007097  0.03953302]
   [0.2059822  0.7052664  0.01029772]
   [0.15658402 0.9865324  0.0746167 ]
   [0.36555228 0.7626717  0.02349186]
   [0.35865265 0.60947365 0.01654992]
   [0.63591397 0.6056242  0.11236238]
   [0.66205573 0.60628957 0.12401301]
   [0.66145474 0.60257125 0.05282515]
   [0.6856064  0.5112026  0.02717525]
   [0.8343023  0.7206725  0.03813615]
   [0.8270198  0.58441925 0.0426695 ]
   [0.84883153 0.5152558  0.03646055]
   [0.85408086 0.46405143 0.04393163]
   [0.8908033  0.44137666 0.02148834]
   [0.8653468  0.35663265 0.03125039]]]]
[[[[0.12020668 0.47800267 0.02748445]
   [0.10998921 0.47540277 0.02338731]
   [0.11492719 0.4475578  0.02024615]
   [0.05295793 0.838371   0.02255559]
   [0.20130041 0.9931206  0.06295252]
   [0.25833052 0.74205804 0.05523658]
   [0.23261063 0.61987996 0.06438214]
   [0.615252   0.655852   0.11130187]
   [0.6333393  0.512699   0.148523  ]
   [0.837

[[[[0.30926138 0.9936266  0.03208011]
   [0.11941442 0.6908499  0.0085175 ]
   [0.29937607 0.829544   0.01713151]
   [0.12278311 0.66421205 0.00800824]
   [0.21587108 0.7665303  0.02519679]
   [0.2286368  0.7273977  0.02340329]
   [0.2661251  0.63990843 0.05390078]
   [0.5155132  0.7297685  0.07774088]
   [0.5243347  0.50702834 0.06803635]
   [0.6815572  0.67899585 0.03646314]
   [0.66426116 0.49397478 0.04051781]
   [0.8478514  0.6977488  0.09840891]
   [0.85730577 0.5451233  0.06189635]
   [1.0074444  0.5690338  0.01155436]
   [1.0092452  0.56007564 0.01328978]
   [1.0061209  0.5430145  0.01459989]
   [1.0057724  0.5767854  0.01489735]]]]
[[[[0.33722335 0.6045023  0.01003963]
   [0.28519377 0.6183068  0.00988612]
   [0.26096156 0.57595897 0.00828442]
   [0.24732046 0.63183665 0.01116419]
   [0.22694157 0.5282917  0.01219153]
   [0.38336253 0.6682755  0.03074569]
   [0.34879982 0.49733132 0.02319899]
   [0.5721823  0.645303   0.05432424]
   [0.53747773 0.46940443 0.03528103]
   [0.635

[[[[0.4319019  0.849193   0.09886131]
   [0.35406613 0.8797449  0.08272046]
   [0.33063155 0.7588684  0.10010371]
   [0.4044691  0.90155303 0.05601144]
   [0.40495834 0.6773254  0.12066838]
   [0.661265   0.9926643  0.02842134]
   [0.7483544  0.38818377 0.77284026]
   [0.79634845 0.977169   0.03127939]
   [0.7523055  0.37504992 0.01002491]
   [0.77861464 0.9807465  0.02277458]
   [0.5028921  0.62310225 0.05230436]
   [0.85342455 0.8253166  0.01723883]
   [0.8949768  0.9115647  0.03705138]
   [0.85607815 0.9769699  0.02663296]
   [0.7447717  0.38530418 0.02725619]
   [0.4724662  0.64092416 0.02420318]
   [0.4000704  0.20749941 0.03375217]]]]
[[[[0.3670436  0.8212372  0.3170821 ]
   [0.31028706 0.8743392  0.19685832]
   [0.31175137 0.7706989  0.23014179]
   [0.35695618 0.94896924 0.20586243]
   [0.37333792 0.7273772  0.26814348]
   [0.67542124 1.0008159  0.03752553]
   [0.6928663  0.40942502 0.79955304]
   [0.8570273  0.96517694 0.04840663]
   [0.6865392  0.3832206  0.01267502]
   [0.535

[[[[0.29794705 0.63160914 0.65841806]
   [0.21321371 0.69014114 0.39412785]
   [0.21133095 0.5745076  0.4549612 ]
   [0.2526478  0.7786538  0.46427855]
   [0.22985533 0.49460965 0.59475285]
   [0.5190614  0.9253222  0.46743426]
   [0.49359524 0.2702285  0.59193414]
   [0.6610298  0.9846639  0.01718405]
   [0.64876485 0.13486075 0.04357579]
   [0.46989247 0.87215745 0.03273943]
   [0.31121892 0.12798768 0.04793009]
   [0.95378774 0.7502154  0.01846099]
   [0.37004203 0.17504965 0.01941496]
   [0.682507   0.97805214 0.00721934]
   [0.34349513 0.1507912  0.03863671]
   [0.28468075 0.16659349 0.03284079]
   [0.29285362 0.1469771  0.045212  ]]]]
[[[[0.18573606 0.63206756 0.70250124]
   [0.1112348  0.700176   0.49113354]
   [0.11219291 0.57188725 0.6104597 ]
   [0.14940557 0.7798066  0.55455387]
   [0.14236607 0.48275253 0.5854765 ]
   [0.44297737 0.9048203  0.71620166]
   [0.3971582  0.26890415 0.7913988 ]
   [0.7209654  0.9713416  0.01895955]
   [0.8219885  0.00965056 0.32442275]
   [0.971

[[[[0.53233314 0.49289116 0.70899796]
   [0.44281015 0.5591272  0.46686828]
   [0.42725605 0.4251526  0.66178495]
   [0.42177582 0.6136383  0.6915748 ]
   [0.39697537 0.3221749  0.61323655]
   [0.63252515 0.6852199  0.65889126]
   [0.5559284  0.11805314 0.5005615 ]
   [0.88191426 0.7664785  0.16323844]
   [0.85267615 0.00310715 0.06692591]
   [0.89048094 0.7426444  0.01715344]
   [0.8688432  0.00297331 0.02065873]
   [0.5545196  0.4728319  0.04912013]
   [0.91048694 0.13140105 0.05264533]
   [0.8611312  0.75732625 0.00950885]
   [0.55874956 0.0966419  0.02459621]
   [0.8578908  0.76657975 0.00267333]
   [1.0001497  0.00253683 0.01343727]]]]
[[[[0.5568806  0.50295264 0.53545856]
   [0.46695897 0.56696045 0.49767247]
   [0.45621055 0.43202078 0.61928356]
   [0.4419964  0.6152163  0.676647  ]
   [0.40752566 0.32460347 0.7426895 ]
   [0.63505983 0.6833615  0.6196921 ]
   [0.5836363  0.10714185 0.61258227]
   [0.8834275  0.76127076 0.08100179]
   [0.8696301  0.00883754 0.05604866]
   [0.873

[[[[5.4834855e-01 2.3889259e-01 6.0040569e-01]
   [4.8674449e-01 3.0416867e-01 6.3322830e-01]
   [4.5852786e-01 1.8580148e-01 5.0321311e-01]
   [4.9448928e-01 3.4760612e-01 4.2366955e-01]
   [4.3509859e-01 9.3037270e-02 6.6114438e-01]
   [6.5657741e-01 4.0056646e-01 6.4089763e-01]
   [5.9126174e-01 1.2590772e-02 1.9798070e-01]
   [8.5823894e-01 4.2972463e-01 1.7433852e-02]
   [8.4842491e-01 7.5721517e-03 3.0346096e-02]
   [6.5881467e-01 3.5856006e-01 1.4279455e-02]
   [6.7214954e-01 1.7333955e-02 2.0511121e-02]
   [5.5094457e-01 1.7042413e-01 1.7423064e-02]
   [3.5397679e-01 1.1450499e-02 1.5849292e-02]
   [6.4617503e-01 4.0085560e-01 1.4655709e-02]
   [8.4916371e-01 5.5964664e-04 1.3783783e-02]
   [5.4313284e-01 2.3556559e-01 1.3851881e-02]
   [8.4676361e-01 1.4183460e-02 1.5787333e-02]]]]
[[[[0.5331079  0.22025913 0.6305648 ]
   [0.47898242 0.28338253 0.41206717]
   [0.44218892 0.17491071 0.5157063 ]
   [0.49544227 0.3301358  0.3770225 ]
   [0.41412005 0.07514594 0.41082698]
   [0.66

[[[[0.53696865 0.76901424 0.53742725]
   [0.46835265 0.8169714  0.5861587 ]
   [0.4779111  0.7036109  0.59993684]
   [0.49172196 0.8843378  0.5367292 ]
   [0.5137743  0.6475365  0.5783475 ]
   [0.69604194 0.9937557  0.22686541]
   [0.78031564 0.53638655 0.5401953 ]
   [0.79833573 0.99057335 0.0224179 ]
   [0.9431666  0.5308541  0.03655994]
   [0.3683709  0.9557612  0.12950379]
   [0.7830602  0.6578523  0.01246533]
   [0.38827837 0.98287964 0.03882724]
   [0.33155227 0.9163477  0.04532722]
   [0.81409633 0.99170965 0.00715828]
   [0.7973823  0.5282103  0.01888841]
   [0.3422109  0.96410906 0.04054633]
   [0.76191086 0.6214366  0.00214657]]]]
[[[[0.4874789  0.77143645 0.58408505]
   [0.4059273  0.82686085 0.70564324]
   [0.421268   0.69786525 0.6281714 ]
   [0.42383164 0.90267533 0.52386475]
   [0.46035022 0.6399226  0.68345666]
   [0.671371   0.9987704  0.1283805 ]
   [0.7379948  0.52292794 0.64763796]
   [0.7629458  0.9919998  0.01513597]
   [0.87176436 0.52332777 0.01871565]
   [0.621

[[[[0.487395   0.659601   0.7749114 ]
   [0.41628993 0.71216357 0.6561913 ]
   [0.4161784  0.5883381  0.5331902 ]
   [0.44404745 0.76980925 0.52672863]
   [0.4484586  0.51123893 0.75127745]
   [0.711216   0.910643   0.64808136]
   [0.73014677 0.39285192 0.79583   ]
   [0.8438108  0.9841602  0.04272944]
   [0.8782951  0.37567347 0.02096865]
   [0.5937718  0.9210967  0.04189837]
   [0.37442827 0.84901524 0.02824661]
   [0.5234178  0.9816818  0.03322494]
   [0.3691334  0.8577368  0.03369454]
   [0.73528266 0.97202003 0.04189479]
   [0.73252386 0.39326054 0.00777063]
   [0.59259456 0.9417183  0.02387255]
   [0.57269704 0.97397876 0.01883191]]]]
[[[[0.4863084  0.65975326 0.73890054]
   [0.41551125 0.7120108  0.63249034]
   [0.41693398 0.58821535 0.5619764 ]
   [0.442106   0.7705585  0.51809055]
   [0.4507807  0.511367   0.76850975]
   [0.71567976 0.90832984 0.63865566]
   [0.7282829  0.39162046 0.73002034]
   [0.8427713  0.9828793  0.0470776 ]
   [0.904976   0.3908591  0.01217142]
   [0.592

[[[[0.51468515 0.6548132  0.78359985]
   [0.44482893 0.708534   0.6426899 ]
   [0.4477712  0.58786094 0.7487935 ]
   [0.46571696 0.77185345 0.5706027 ]
   [0.47335896 0.5135634  0.7246096 ]
   [0.73963517 0.9180436  0.61164904]
   [0.7486719  0.39209113 0.70749944]
   [0.87274855 0.98703283 0.02504855]
   [0.9759276  0.38604772 0.02756634]
   [0.604717   0.9222285  0.03567907]
   [0.8836789  0.32694206 0.01077989]
   [1.0167919  0.88011587 0.01489848]
   [0.39203557 0.8510684  0.03529093]
   [0.8442894  0.98167074 0.01580018]
   [0.76249385 0.40519673 0.00666848]
   [0.55445623 0.98338145 0.0218676 ]
   [0.3481673  0.14720199 0.02383581]]]]
[[[[0.5144071  0.654812   0.7683511 ]
   [0.4445907  0.7072531  0.6264899 ]
   [0.44734812 0.5874275  0.72927576]
   [0.46416265 0.7713047  0.54195625]
   [0.47147685 0.5120841  0.74820197]
   [0.7330861  0.918942   0.6051173 ]
   [0.7491583  0.390341   0.7797146 ]
   [0.83141065 0.98351645 0.02588174]
   [0.87509036 0.37095922 0.03531817]
   [0.618

[[[[0.5147708  0.65219647 0.71726036]
   [0.44241306 0.70249915 0.8074736 ]
   [0.44893318 0.5809202  0.5882592 ]
   [0.456632   0.7646612  0.5324563 ]
   [0.4737373  0.5061705  0.7135139 ]
   [0.7349433  0.9181824  0.65924084]
   [0.74965775 0.3876246  0.8051131 ]
   [0.85153306 0.98542947 0.02602506]
   [0.9756922  0.38642037 0.02624875]
   [0.73775613 0.8795075  0.00857487]
   [0.9444062  0.48852396 0.00810927]
   [0.42841244 0.83777416 0.02135417]
   [0.3741227  0.848943   0.02557716]
   [0.8097977  0.9779121  0.01805791]
   [0.7645111  0.38221288 0.01071194]
   [0.7203349  0.94972557 0.00372511]
   [0.7620084  0.00954817 0.00828612]]]]
[[[[0.51581734 0.6477119  0.6604862 ]
   [0.44094798 0.6995677  0.8133893 ]
   [0.44966596 0.57650685 0.72860914]
   [0.45632336 0.76378584 0.5626844 ]
   [0.47497436 0.50538605 0.7082361 ]
   [0.73620224 0.91807973 0.6254828 ]
   [0.75109506 0.38702863 0.77794635]
   [0.8320137  0.98310375 0.02812064]
   [0.9755647  0.38975918 0.0264672 ]
   [0.736

[[[[0.6168619  0.6428571  0.5705352 ]
   [0.5490954  0.69386697 0.77065665]
   [0.5540907  0.57752347 0.6432396 ]
   [0.5733671  0.75434417 0.6291257 ]
   [0.5845915  0.5108937  0.595146  ]
   [0.82453847 0.8905822  0.6061038 ]
   [0.85485923 0.40220293 0.72227496]
   [0.9613041  0.96197855 0.04746386]
   [0.9551064  0.3580321  0.03539908]
   [0.5963658  0.9102614  0.06503257]
   [0.8684008  0.12777826 0.04662028]
   [0.89051497 0.06805153 0.06341904]
   [0.90016687 0.2264313  0.04841128]
   [0.8568639  0.9679281  0.02702767]
   [0.86683476 0.3852895  0.03389221]
   [0.67749995 0.9934958  0.01513928]
   [0.8507283  0.2110225  0.01835746]]]]
[[[[0.61397886 0.647618   0.64902604]
   [0.546625   0.6954886  0.7710457 ]
   [0.5522529  0.581558   0.56946534]
   [0.5730156  0.7543906  0.5893631 ]
   [0.58391964 0.5151736  0.59073734]
   [0.8248764  0.8924779  0.64072025]
   [0.8477037  0.40819725 0.7019522 ]
   [0.96115136 0.9616449  0.04748392]
   [0.951384   0.34350425 0.04384616]
   [0.705

[[[[0.59090376 0.71400535 0.801987  ]
   [0.53863525 0.7436506  0.5769258 ]
   [0.53455436 0.6549064  0.7118828 ]
   [0.56360435 0.7631912  0.34693867]
   [0.5674088  0.55416435 0.7138365 ]
   [0.81444883 0.8919959  0.5814309 ]
   [0.844928   0.4204913  0.7479006 ]
   [0.95834374 0.96231496 0.04888341]
   [0.9538065  0.38412532 0.04026374]
   [0.67274565 0.95729876 0.06692079]
   [0.86226666 0.51372415 0.00717649]
   [0.49386072 0.9000006  0.02630609]
   [0.4810105  0.88212794 0.02810749]
   [0.843975   0.97100806 0.03609049]
   [0.85563445 0.4257029  0.02841985]
   [0.5978523  0.97498554 0.0228911 ]
   [0.5868087  0.9043781  0.00705546]]]]
[[[[0.586521   0.7098233  0.6469742 ]
   [0.53025186 0.7487893  0.6708676 ]
   [0.53296685 0.65211505 0.6947038 ]
   [0.5574856  0.7920036  0.40082   ]
   [0.5676319  0.5695863  0.6344428 ]
   [0.7969799  0.9010292  0.49299255]
   [0.80919427 0.4370316  0.73724926]
   [0.87331885 0.9748522  0.02874798]
   [0.9527396  0.4013391  0.04794839]
   [0.586

[[[[0.40803003 0.4731685  0.7191185 ]
   [0.32519367 0.5359928  0.71221906]
   [0.3143034  0.41575763 0.606002  ]
   [0.32447225 0.5730743  0.6876415 ]
   [0.29531813 0.3164267  0.65519184]
   [0.5207926  0.62078655 0.73353195]
   [0.49148208 0.12318577 0.7178786 ]
   [0.8640196  0.6717551  0.5304254 ]
   [0.8752825  0.03728617 0.21004197]
   [0.88624954 0.67914546 0.07172295]
   [0.8792497  0.17295685 0.01996088]
   [0.86320806 0.4481617  0.14884627]
   [0.8597752  0.17826506 0.24542665]
   [0.8649696  0.64637583 0.01454759]
   [0.85374534 0.12864405 0.04147318]
   [0.8916158  0.67745674 0.00804839]
   [0.86577195 0.17016803 0.01680273]]]]
[[[[0.44151455 0.49256235 0.59606904]
   [0.36374718 0.5410355  0.54342914]
   [0.34962153 0.44287357 0.521995  ]
   [0.3588111  0.5461234  0.4659161 ]
   [0.30422992 0.3292442  0.6523437 ]
   [0.55036557 0.61786914 0.64857984]
   [0.5022148  0.1396005  0.70883316]
   [0.87884635 0.6709478  0.10778159]
   [0.6346589  0.04152214 0.05656925]
   [0.863

[[[[0.05616796 0.747606   0.03984115]
   [0.03447364 0.7886342  0.03439161]
   [0.03365116 0.7151503  0.04765791]
   [0.10740319 0.8079683  0.16264927]
   [0.1006389  0.6463598  0.12386659]
   [0.2785051  0.854321   0.44635972]
   [0.23278672 0.4827102  0.8151134 ]
   [0.59347135 0.79920125 0.15252164]
   [0.5717342  0.35626435 0.636641  ]
   [0.84207153 0.7179142  0.09978303]
   [0.86666363 0.33783805 0.24850366]
   [0.8727459  0.8840191  0.2305403 ]
   [0.87353843 0.5508638  0.31390584]
   [0.87928814 0.8831007  0.02980492]
   [1.0095663  0.6083803  0.0089387 ]
   [0.977064   0.75500333 0.01701054]
   [1.0010772  0.56913555 0.00934619]]]]
[[[[0.06329243 0.66978216 0.03279775]
   [0.03112456 0.69122076 0.02424148]
   [0.03079654 0.68706536 0.02883482]
   [0.10313469 0.6891179  0.08453783]
   [0.11058688 0.75877213 0.14682627]
   [0.2358737  0.49168426 0.63473976]
   [0.2794111  0.8842012  0.83274543]
   [0.5745423  0.41795397 0.06798133]
   [0.5723578  0.33164054 0.68254817]
   [0.798

[[[[0.36209494 0.6153636  0.79965377]
   [0.33351046 0.64414465 0.54170287]
   [0.33550686 0.5875073  0.52171236]
   [0.34811145 0.6849121  0.7220581 ]
   [0.34638903 0.55373514 0.7845433 ]
   [0.4914325  0.76132834 0.5542658 ]
   [0.4999702  0.4772713  0.88013315]
   [0.71367145 0.8230133  0.66369414]
   [0.7036265  0.41389805 0.7979077 ]
   [0.8711374  0.87581325 0.36786798]
   [0.8685767  0.37998483 0.37575814]
   [0.8743865  0.7228574  0.4934717 ]
   [0.8720326  0.5257348  0.55999553]
   [0.8692919  0.833274   0.01165915]
   [0.87455034 0.44720376 0.00772229]
   [0.98651093 0.88013864 0.0339711 ]
   [0.88696784 0.38008374 0.0184367 ]]]]
[[[[0.36209494 0.6153636  0.79965377]
   [0.33351046 0.64414465 0.54170287]
   [0.33550686 0.5875073  0.52171236]
   [0.34811145 0.6849121  0.7220581 ]
   [0.34638903 0.55373514 0.7845433 ]
   [0.4914325  0.76132834 0.5542658 ]
   [0.4999702  0.4772713  0.88013315]
   [0.71367145 0.8230133  0.66369414]
   [0.7036265  0.41389805 0.7979077 ]
   [0.871

[[[[0.36334962 0.55904233 0.6803052 ]
   [0.34078607 0.5841383  0.62027884]
   [0.34209785 0.53553724 0.7873658 ]
   [0.36171603 0.62259793 0.7451798 ]
   [0.36501068 0.50529534 0.788263  ]
   [0.49147794 0.70196956 0.6377436 ]
   [0.5035115  0.43500394 0.89983726]
   [0.6661808  0.79418087 0.78322697]
   [0.6799356  0.35097337 0.7473837 ]
   [0.8275088  0.7902731  0.570281  ]
   [0.8354029  0.37079012 0.6232527 ]
   [0.86611176 0.65538406 0.5211209 ]
   [0.86404634 0.4662935  0.6279615 ]
   [0.86297953 0.7285513  0.010461  ]
   [0.86988395 0.4065605  0.01109377]
   [1.0053562  0.77094454 0.01323816]
   [0.86543024 0.39968836 0.02080402]]]]
[[[[0.36402905 0.5595565  0.6359051 ]
   [0.34036058 0.5842532  0.62424934]
   [0.34232578 0.53620267 0.78125   ]
   [0.361167   0.6230388  0.49136364]
   [0.36487418 0.5062517  0.8013806 ]
   [0.48780042 0.70092463 0.7623088 ]
   [0.5022516  0.43488562 0.841637  ]
   [0.6674413  0.7888078  0.7716832 ]
   [0.67503107 0.3621651  0.7029656 ]
   [0.834

[[[[0.36376458 0.5790694  0.73434424]
   [0.33880937 0.60008705 0.5423566 ]
   [0.34102798 0.55235994 0.771235  ]
   [0.35934997 0.63836163 0.7550291 ]
   [0.36240336 0.52156764 0.68049985]
   [0.48960942 0.72403324 0.6402659 ]
   [0.5002802  0.45256135 0.9141978 ]
   [0.6894827  0.79494256 0.79039   ]
   [0.6882917  0.36902088 0.81273675]
   [0.8637246  0.8368114  0.3071902 ]
   [0.8520975  0.3609482  0.51342845]
   [0.8655039  0.6839224  0.19443151]
   [0.85988235 0.4934146  0.147836  ]
   [0.8655629  0.78869814 0.00562039]
   [0.8619265  0.3846775  0.01138279]
   [1.0088503  0.8515298  0.01923847]
   [0.86637735 0.36525178 0.01703757]]]]
[[[[0.36376458 0.5790694  0.73434424]
   [0.33880937 0.60008705 0.5423566 ]
   [0.34102798 0.55235994 0.771235  ]
   [0.35934997 0.63836163 0.7550291 ]
   [0.36240336 0.52156764 0.68049985]
   [0.48960942 0.72403324 0.6402659 ]
   [0.5002802  0.45256135 0.9141978 ]
   [0.6894827  0.79494256 0.79039   ]
   [0.6882917  0.36902088 0.81273675]
   [0.863

[[[[0.37118086 0.584166   0.6259844 ]
   [0.34797472 0.606838   0.71350485]
   [0.34982818 0.5613072  0.58923936]
   [0.36190245 0.642493   0.49322125]
   [0.36595398 0.52906555 0.8262925 ]
   [0.46285433 0.70381427 0.81151813]
   [0.4687792  0.47565162 0.8612157 ]
   [0.58476    0.7990118  0.6053351 ]
   [0.5894388  0.3994192  0.7169358 ]
   [0.6922759  0.868968   0.6292909 ]
   [0.66851795 0.3387844  0.67330253]
   [0.8030218  0.66949713 0.2727726 ]
   [0.8120073  0.51783586 0.35181195]
   [0.84913373 0.7827798  0.03210974]
   [0.8576971  0.49094427 0.03026512]
   [0.7657975  0.86992455 0.05267906]
   [0.7407958  0.32210165 0.04723072]]]]
[[[[0.36768353 0.58477724 0.6491225 ]
   [0.3451671  0.60742855 0.73487276]
   [0.34772372 0.5618428  0.62520754]
   [0.35968098 0.6449635  0.48629552]
   [0.36352977 0.5293766  0.8104522 ]
   [0.45534152 0.7019155  0.6755453 ]
   [0.45968527 0.47998077 0.8136469 ]
   [0.5722207  0.8048624  0.6845733 ]
   [0.5702568  0.40260458 0.82042897]
   [0.689

[[[[0.41852617 0.5358412  0.41183737]
   [0.39499664 0.56084657 0.4484298 ]
   [0.3946677  0.52157444 0.44201985]
   [0.40887564 0.6023569  0.54108065]
   [0.4062853  0.4996754  0.63122636]
   [0.5247282  0.66764224 0.81627566]
   [0.51522064 0.43120846 0.7652418 ]
   [0.72027177 0.7190284  0.7529334 ]
   [0.67076504 0.36400008 0.69937557]
   [0.87420315 0.7625786  0.34020406]
   [0.7726773  0.30531168 0.54709065]
   [0.8725548  0.62216765 0.7046631 ]
   [0.86872435 0.4525381  0.76626134]
   [0.99558425 0.7545764  0.026847  ]
   [0.88009685 0.36635685 0.02747235]
   [1.0065677  0.6381072  0.01184443]
   [1.0038948  0.45634365 0.00701267]]]]
[[[[0.43607315 0.530162   0.58640814]
   [0.41564855 0.55117595 0.5604217 ]
   [0.41556665 0.5111971  0.6277422 ]
   [0.42720637 0.5768465  0.4906445 ]
   [0.42262602 0.48259956 0.62548614]
   [0.531505   0.6400151  0.7467477 ]
   [0.5233506  0.4174572  0.8332504 ]
   [0.7077452  0.7067827  0.6707041 ]
   [0.6659336  0.35317755 0.7190482 ]
   [0.861

[[[[0.3341285  0.5563091  0.3792349 ]
   [0.24209136 0.6104697  0.54930335]
   [0.247206   0.48834497 0.6082338 ]
   [0.2407659  0.6764766  0.71576   ]
   [0.258808   0.41917384 0.6348479 ]
   [0.37540835 0.7882533  0.7701602 ]
   [0.45878333 0.35528862 0.8557656 ]
   [0.452115   0.9742693  0.14228517]
   [0.8438935  0.2774952  0.357633  ]
   [0.49694228 0.9343474  0.05675563]
   [0.8545553  0.35900337 0.05477411]
   [0.8071539  0.73409456 0.40469152]
   [0.81633896 0.49435925 0.4776532 ]
   [0.8615136  0.7654063  0.0241223 ]
   [0.8376163  0.39950383 0.10987464]
   [0.8544389  0.7596762  0.00921765]
   [0.84431696 0.44582972 0.03883153]]]]
[[[[0.3227795  0.57123095 0.57703936]
   [0.22636592 0.6250257  0.33628935]
   [0.23724914 0.5025844  0.4527551 ]
   [0.204339   0.69514537 0.53512484]
   [0.21951127 0.42777655 0.6920327 ]
   [0.32727617 0.7887358  0.66814613]
   [0.41142246 0.36154413 0.8218198 ]
   [0.4197492  0.977286   0.12530512]
   [0.7838659  0.2837078  0.46034998]
   [0.470

[[[[0.3892274  0.5898932  0.6612961 ]
   [0.31133693 0.6484022  0.50502294]
   [0.3058446  0.527006   0.7448158 ]
   [0.30965817 0.7135763  0.68839204]
   [0.30243772 0.45375258 0.62349486]
   [0.41428447 0.8050145  0.61099744]
   [0.478582   0.38692844 0.8628199 ]
   [0.49445218 0.97958183 0.24852619]
   [0.83455    0.29374254 0.48562542]
   [0.5063261  0.9902915  0.06333011]
   [0.8682033  0.27428898 0.02782947]
   [0.80616134 0.75021005 0.6556896 ]
   [0.82098806 0.50963014 0.83535326]
   [0.8491558  0.9724776  0.12162331]
   [0.8489341  0.32764    0.11582175]
   [0.8762106  0.7571845  0.01343581]
   [0.87247205 0.5601893  0.01845118]]]]
[[[[0.40443942 0.5836763  0.5763326 ]
   [0.32493886 0.6439825  0.61463445]
   [0.32327598 0.52374566 0.74045026]
   [0.3196054  0.7110481  0.6439728 ]
   [0.3113565  0.45670313 0.49636137]
   [0.42820212 0.8064085  0.56277514]
   [0.47761774 0.39447784 0.84490794]
   [0.50047326 0.9736978  0.15491915]
   [0.81264484 0.30192095 0.45601475]
   [0.557

[[[[0.434218   0.53613394 0.641947  ]
   [0.41064903 0.55726814 0.66494   ]
   [0.40771985 0.5149697  0.7144265 ]
   [0.41803774 0.58390045 0.42800927]
   [0.41245276 0.48261452 0.5154405 ]
   [0.5382089  0.6424037  0.64674616]
   [0.5438109  0.41521198 0.72610104]
   [0.7068447  0.68740714 0.6693033 ]
   [0.6950731  0.36998352 0.63929546]
   [0.85954666 0.7189964  0.60483634]
   [0.85419023 0.36313757 0.58373636]
   [0.87209547 0.6158332  0.74383247]
   [0.8722569  0.45903644 0.6898383 ]
   [1.0160583  0.7117555  0.00895944]
   [1.0242119  0.38847408 0.00678056]
   [1.0114834  0.6405622  0.00799066]
   [1.0251187  0.53630996 0.00307813]]]]
[[[[0.45447868 0.535704   0.6338088 ]
   [0.43104288 0.554893   0.7463473 ]
   [0.43001732 0.5142741  0.7327975 ]
   [0.43806243 0.5826844  0.4402602 ]
   [0.43629712 0.487597   0.6348913 ]
   [0.5499824  0.6416116  0.7239634 ]
   [0.55713356 0.43330312 0.860234  ]
   [0.7064804  0.6897659  0.6364282 ]
   [0.7015953  0.38398916 0.644576  ]
   [0.858

[[[[0.48066115 0.5149592  0.5055214 ]
   [0.46561682 0.5311136  0.6214146 ]
   [0.46605188 0.4979838  0.57798284]
   [0.4782989  0.557024   0.52201664]
   [0.4790641  0.4737186  0.58476573]
   [0.5791977  0.609638   0.6156572 ]
   [0.58025265 0.4225447  0.674212  ]
   [0.72566295 0.6522699  0.6417048 ]
   [0.7104344  0.38764125 0.5557474 ]
   [0.8590335  0.67735994 0.53894866]
   [0.8543343  0.3651323  0.5800074 ]
   [0.8591108  0.58034885 0.7600479 ]
   [0.8603709  0.4477496  0.7962271 ]
   [0.8925084  0.61125576 0.0158397 ]
   [0.8864682  0.3935606  0.0119521 ]
   [0.9877279  0.59841645 0.02047688]
   [0.9999477  0.45777673 0.01194352]]]]
[[[[0.4798532  0.51403844 0.51953405]
   [0.46479568 0.529822   0.6070959 ]
   [0.46583888 0.49725318 0.59935975]
   [0.4776977  0.5562836  0.50599444]
   [0.47937736 0.47395885 0.58707553]
   [0.5785995  0.6058512  0.5803127 ]
   [0.5798577  0.42555547 0.6720724 ]
   [0.7195436  0.65219784 0.5206514 ]
   [0.7093786  0.3874746  0.53899485]
   [0.855

[[[[0.47581893 0.51482135 0.5626323 ]
   [0.4611441  0.5299766  0.544442  ]
   [0.4631271  0.49905106 0.37888274]
   [0.47726625 0.5580648  0.5360949 ]
   [0.47917876 0.47950113 0.5340137 ]
   [0.572147   0.6125241  0.8028313 ]
   [0.57556397 0.42516112 0.61118585]
   [0.7196851  0.65835834 0.62831616]
   [0.7095574  0.3882067  0.68458986]
   [0.8529784  0.6810674  0.5382883 ]
   [0.850649   0.36403346 0.61337477]
   [0.85855436 0.58708453 0.7480656 ]
   [0.8589572  0.45172685 0.7962276 ]
   [0.9137897  0.6252151  0.0111616 ]
   [0.8845391  0.3958082  0.01151532]
   [0.98507774 0.59817445 0.0229767 ]
   [0.997234   0.45767182 0.01157737]]]]
[[[[0.47497165 0.5062516  0.5904488 ]
   [0.45922482 0.52339154 0.47728187]
   [0.46205148 0.492349   0.41295326]
   [0.47665012 0.5552224  0.65725094]
   [0.4766369  0.47553176 0.5741936 ]
   [0.57374954 0.61089385 0.7917693 ]
   [0.57688296 0.42505056 0.6397105 ]
   [0.71921885 0.6577296  0.59053934]
   [0.70988    0.38874346 0.730818  ]
   [0.853

[[[[0.47331917 0.5072615  0.6340923 ]
   [0.45855653 0.52488685 0.44728833]
   [0.4614293  0.4938209  0.41536793]
   [0.47795206 0.55782837 0.55197674]
   [0.47869784 0.48039347 0.5164041 ]
   [0.57329744 0.61477166 0.7900518 ]
   [0.57961154 0.429198   0.6957848 ]
   [0.71496105 0.65423024 0.5607013 ]
   [0.71588844 0.39184558 0.74849194]
   [0.8511543  0.6807506  0.50857675]
   [0.84310365 0.36317378 0.6632615 ]
   [0.85364795 0.583472   0.7588483 ]
   [0.8579122  0.45602557 0.6791705 ]
   [0.9840807  0.6223118  0.01902226]
   [0.8849163  0.39479965 0.01231599]
   [0.98809063 0.61836076 0.01998317]
   [1.0090567  0.46058604 0.00859621]]]]
[[[[0.47331917 0.5072615  0.6340923 ]
   [0.45855653 0.52488685 0.44728833]
   [0.4614293  0.4938209  0.41536793]
   [0.47795206 0.55782837 0.55197674]
   [0.47869784 0.48039347 0.5164041 ]
   [0.57329744 0.61477166 0.7900518 ]
   [0.57961154 0.429198   0.6957848 ]
   [0.71496105 0.65423024 0.5607013 ]
   [0.71588844 0.39184558 0.74849194]
   [0.851

[[[[0.5025947  0.5336396  0.5485978 ]
   [0.48328394 0.5504551  0.50042397]
   [0.48359692 0.52181005 0.62143004]
   [0.4930337  0.5819116  0.5610771 ]
   [0.49098378 0.50458455 0.54144806]
   [0.60273653 0.62157464 0.5596354 ]
   [0.556829   0.47482345 0.6315905 ]
   [0.7401823  0.63172877 0.5825138 ]
   [0.4494023  0.39663312 0.49784288]
   [0.7713584  0.522568   0.31476796]
   [0.4064684  0.39990973 0.16403371]
   [0.8639773  0.55467397 0.4195417 ]
   [0.845623   0.44350132 0.6161442 ]
   [0.98637354 0.55616426 0.03769678]
   [0.8597429  0.39730722 0.03180584]
   [0.8498986  0.44621056 0.02184093]
   [0.827497   0.48610112 0.01966   ]]]]
[[[[0.49827307 0.5288938  0.5451239 ]
   [0.47946364 0.5495106  0.5372374 ]
   [0.47565353 0.51399356 0.5033601 ]
   [0.49099636 0.57582116 0.6414821 ]
   [0.488229   0.4969078  0.59753823]
   [0.5843906  0.6175395  0.67773676]
   [0.5489675  0.4581452  0.72344476]
   [0.71854085 0.6367285  0.4280661 ]
   [0.44102347 0.4016386  0.69978356]
   [0.735

[[[[0.49564478 0.5153209  0.47714818]
   [0.4737177  0.53906226 0.59360886]
   [0.4737253  0.4949687  0.3607723 ]
   [0.48493165 0.5644514  0.60000896]
   [0.48246762 0.47603738 0.57165354]
   [0.599496   0.6115118  0.5096004 ]
   [0.5499222  0.43347856 0.7159621 ]
   [0.70635694 0.65473086 0.32626748]
   [0.42568588 0.39000666 0.6285267 ]
   [0.5078539  0.6577064  0.22247547]
   [0.4493227  0.4910162  0.16787106]
   [0.8645021  0.57442546 0.51932496]
   [0.8662912  0.43366998 0.5517909 ]
   [0.84859717 0.6532512  0.05239353]
   [0.8443111  0.37852928 0.04480702]
   [0.99531287 0.6734421  0.02985671]
   [0.8721305  0.46469164 0.00596124]]]]
[[[[0.49773717 0.5143489  0.5207827 ]
   [0.47404763 0.5372865  0.63096094]
   [0.47447795 0.49448025 0.5517034 ]
   [0.48601407 0.56274724 0.5752358 ]
   [0.48183376 0.46999103 0.6364298 ]
   [0.5994649  0.61916965 0.6776104 ]
   [0.5521196  0.42955393 0.7374341 ]
   [0.7672385  0.6417418  0.50770044]
   [0.42079806 0.38784128 0.54427576]
   [0.694

[[[[0.4910128  0.51404375 0.6803864 ]
   [0.47172698 0.5339781  0.6900916 ]
   [0.47097015 0.49564517 0.57216156]
   [0.48560914 0.5607238  0.59345555]
   [0.4822163  0.4705326  0.6554388 ]
   [0.5972258  0.60628587 0.6268662 ]
   [0.5495527  0.4356398  0.7294606 ]
   [0.7418351  0.6554323  0.47012478]
   [0.41929734 0.38255894 0.5043032 ]
   [0.69975257 0.6726352  0.30204952]
   [0.3518769  0.4057212  0.14054811]
   [0.86497474 0.57822883 0.5181632 ]
   [0.8622124  0.44082582 0.4352483 ]
   [0.841213   0.66721576 0.05311149]
   [0.83940136 0.41687068 0.03096852]
   [0.98110175 0.67552817 0.00962889]
   [0.9025482  0.47713906 0.00584689]]]]
[[[[0.4917767  0.5118904  0.6799311 ]
   [0.47185963 0.5315255  0.6905736 ]
   [0.4724254  0.4937759  0.67342025]
   [0.48369643 0.5608309  0.5867391 ]
   [0.48185024 0.4696009  0.6191368 ]
   [0.58607364 0.6183507  0.6999833 ]
   [0.5469159  0.43543792 0.71115553]
   [0.7240628  0.6777181  0.5885776 ]
   [0.44835937 0.38787326 0.6567343 ]
   [0.737

[[[[0.4983171  0.51894754 0.38642532]
   [0.47662532 0.5408558  0.31415212]
   [0.47500715 0.49983758 0.48365268]
   [0.48484218 0.5658156  0.58538574]
   [0.4808241  0.47546023 0.544159  ]
   [0.5895734  0.60927635 0.549515  ]
   [0.54992676 0.4338474  0.7759633 ]
   [0.7024688  0.66234016 0.32988882]
   [0.4930668  0.37905842 0.44318178]
   [0.60735726 0.65443945 0.17431659]
   [0.39165136 0.4494773  0.22852126]
   [0.8779576  0.5771697  0.36694252]
   [0.879006   0.43438035 0.444795  ]
   [0.84335744 0.66171324 0.02691624]
   [0.84775853 0.36756235 0.02809864]
   [1.0150064  0.67859316 0.01505718]
   [1.0172656  0.4638008  0.00323725]]]]
[[[[0.4983171  0.51894754 0.38642532]
   [0.47662532 0.5408558  0.31415212]
   [0.47500715 0.49983758 0.48365268]
   [0.48484218 0.5658156  0.58538574]
   [0.4808241  0.47546023 0.544159  ]
   [0.5895734  0.60927635 0.549515  ]
   [0.54992676 0.4338474  0.7759633 ]
   [0.7024688  0.66234016 0.32988882]
   [0.4930668  0.37905842 0.44318178]
   [0.607

[[[[0.4992071  0.5263508  0.45464027]
   [0.48110372 0.54286987 0.50912887]
   [0.48303542 0.5095668  0.62256885]
   [0.49199936 0.5691619  0.67693025]
   [0.49585104 0.4882725  0.6791667 ]
   [0.57141006 0.60980314 0.64134455]
   [0.5874142  0.43425608 0.66547394]
   [0.6245049  0.639418   0.5089802 ]
   [0.7079809  0.34738943 0.5753218 ]
   [0.5101365  0.6018163  0.3429858 ]
   [0.6187179  0.43134224 0.3789444 ]
   [0.862828   0.5829594  0.7295683 ]
   [0.8617524  0.45343417 0.6530233 ]
   [0.85550666 0.651135   0.0304057 ]
   [0.8604728  0.38831997 0.01570886]
   [0.8726982  0.6188636  0.0124923 ]
   [0.55973935 0.47087026 0.02545682]]]]
[[[[0.49975786 0.52692884 0.44610792]
   [0.4807533  0.5458695  0.50358206]
   [0.4807857  0.5092473  0.5876883 ]
   [0.49170858 0.57532334 0.5961311 ]
   [0.49458718 0.4823621  0.62642217]
   [0.5685934  0.60363454 0.66450727]
   [0.59018826 0.43399066 0.73509413]
   [0.59523374 0.61568457 0.513223  ]
   [0.721754   0.36433256 0.77560884]
   [0.469

[[[[0.49142927 0.4959395  0.69041455]
   [0.47626197 0.51650226 0.63634324]
   [0.47582072 0.4834172  0.503264  ]
   [0.49076366 0.55518824 0.7410472 ]
   [0.48895556 0.47888702 0.53773534]
   [0.57869625 0.5907221  0.6744262 ]
   [0.5846287  0.42825124 0.7453227 ]
   [0.6126039  0.5984213  0.6094462 ]
   [0.7282631  0.36854124 0.6421212 ]
   [0.4932931  0.57319874 0.3826815 ]
   [0.6994847  0.4736324  0.4926288 ]
   [0.8554034  0.5746856  0.5814819 ]
   [0.8529741  0.44705614 0.6060959 ]
   [0.8599616  0.6108358  0.05400243]
   [0.837126   0.3154773  0.05601093]
   [0.8497759  0.6488703  0.03004533]
   [0.8437774  0.58692414 0.02000913]]]]
[[[[0.49124348 0.49527884 0.7317869 ]
   [0.47558212 0.5163449  0.67970765]
   [0.47508094 0.48275906 0.5218992 ]
   [0.49028826 0.5545508  0.7748759 ]
   [0.488373   0.47790134 0.5667365 ]
   [0.57781494 0.58848095 0.7086915 ]
   [0.58311665 0.42401728 0.747351  ]
   [0.6084171  0.59847593 0.56926763]
   [0.7258107  0.36781093 0.6535646 ]
   [0.485

[[[[0.4906406  0.5032268  0.47482148]
   [0.4765442  0.5188937  0.4667437 ]
   [0.4791654  0.4877542  0.4980672 ]
   [0.48708296 0.54404646 0.5637498 ]
   [0.4955563  0.4648723  0.6722579 ]
   [0.55982137 0.59509706 0.65483624]
   [0.5736008  0.42644808 0.8002747 ]
   [0.6240084  0.66627383 0.29902202]
   [0.6659305  0.35160184 0.39809328]
   [0.5051372  0.64864504 0.4923141 ]
   [0.5653507  0.3932758  0.45695272]
   [0.8503971  0.57477766 0.77277184]
   [0.8552     0.44308302 0.7340162 ]
   [0.85743105 0.651742   0.0483329 ]
   [0.8495221  0.37680158 0.02629238]
   [0.87330115 0.64544904 0.01020968]
   [0.54647857 0.43866083 0.03572202]]]]
[[[[0.49261186 0.50445956 0.516785  ]
   [0.47566974 0.52002823 0.42268273]
   [0.47631818 0.48920083 0.50018054]
   [0.4891017  0.5446817  0.71313614]
   [0.48969656 0.46527278 0.7537539 ]
   [0.56636465 0.5961806  0.7350727 ]
   [0.5661655  0.418293   0.79074043]
   [0.5790317  0.6982128  0.3779292 ]
   [0.621132   0.3229323  0.46630925]
   [0.471

[[[[0.49777576 0.518034   0.43854088]
   [0.480182   0.53353167 0.6696664 ]
   [0.4795702  0.50008565 0.5231359 ]
   [0.49318668 0.5604423  0.652678  ]
   [0.4885229  0.4832422  0.6792921 ]
   [0.5672798  0.6116368  0.8010293 ]
   [0.56070787 0.43197498 0.7878537 ]
   [0.551089   0.73128605 0.6496206 ]
   [0.55153286 0.30603185 0.67612815]
   [0.41937694 0.6943582  0.26115924]
   [0.43711767 0.34441444 0.46978632]
   [0.8554122  0.580526   0.7807344 ]
   [0.85940355 0.45561063 0.74330556]
   [0.8501557  0.6633608  0.19866139]
   [0.85375667 0.3019066  0.21265545]
   [0.8880979  0.617183   0.01143754]
   [0.89116025 0.41696262 0.00874129]]]]
[[[[0.49777576 0.518034   0.43854088]
   [0.480182   0.53353167 0.6696664 ]
   [0.4795702  0.50008565 0.5231359 ]
   [0.49318668 0.5604423  0.652678  ]
   [0.4885229  0.4832422  0.6792921 ]
   [0.5672798  0.6116368  0.8010293 ]
   [0.56070787 0.43197498 0.7878537 ]
   [0.551089   0.73128605 0.6496206 ]
   [0.55153286 0.30603185 0.67612815]
   [0.419

[[[[0.49715137 0.5154356  0.5279917 ]
   [0.47910368 0.530565   0.6291967 ]
   [0.47909194 0.49647725 0.4610156 ]
   [0.49353075 0.5596167  0.66876876]
   [0.49079072 0.4799889  0.6083678 ]
   [0.5676589  0.6099702  0.8181356 ]
   [0.56250733 0.43120357 0.80193615]
   [0.5525265  0.72691333 0.6964283 ]
   [0.5513256  0.30659008 0.6877351 ]
   [0.4228757  0.6743819  0.39995292]
   [0.43629512 0.3431078  0.38305208]
   [0.8536395  0.5821895  0.77091086]
   [0.8583468  0.45752847 0.7340964 ]
   [0.8484359  0.65994346 0.1999822 ]
   [0.85312974 0.30903846 0.20446047]
   [0.88519704 0.6143272  0.0114716 ]
   [0.8846731  0.41957873 0.01191589]]]]
[[[[0.49790782 0.5189149  0.45552248]
   [0.4799599  0.53434753 0.67312443]
   [0.47935438 0.5006307  0.5617836 ]
   [0.49455354 0.56022763 0.63626146]
   [0.49018475 0.4842865  0.6916654 ]
   [0.5658674  0.6113847  0.8320191 ]
   [0.5605472  0.43186784 0.7835537 ]
   [0.5549163  0.7300836  0.7019626 ]
   [0.55141056 0.30579334 0.66810673]
   [0.432

[[[[0.49556777 0.5219679  0.4015445 ]
   [0.47858918 0.5402087  0.5717586 ]
   [0.47806108 0.50728554 0.5546056 ]
   [0.4939456  0.56406164 0.64214   ]
   [0.48968208 0.49070153 0.77757746]
   [0.56652117 0.61489177 0.82325196]
   [0.5642622  0.44079578 0.80089796]
   [0.55208415 0.716306   0.6962384 ]
   [0.55495447 0.31488353 0.79887223]
   [0.43360025 0.64944744 0.44950274]
   [0.44194394 0.36309665 0.55727684]
   [0.85118127 0.5841364  0.7808067 ]
   [0.85610163 0.45851633 0.7470774 ]
   [0.8453302  0.66543263 0.27765632]
   [0.8431144  0.30745488 0.27319464]
   [0.8867981  0.5800278  0.02674821]
   [0.8852943  0.42274377 0.02833465]]]]
[[[[0.49499428 0.52056444 0.47441745]
   [0.47836262 0.5385479  0.58416355]
   [0.4775378  0.5056181  0.5094308 ]
   [0.49418566 0.56400764 0.64903617]
   [0.48858008 0.489886   0.7744957 ]
   [0.5659177  0.6122046  0.81626064]
   [0.5633445  0.44153512 0.76088065]
   [0.5569968  0.7208676  0.5343973 ]
   [0.5540774  0.3170921  0.79583085]
   [0.437

[[[[0.49500322 0.543941   0.44376445]
   [0.47375235 0.56198555 0.37693653]
   [0.47468683 0.5257999  0.66567445]
   [0.48459345 0.59082764 0.7474903 ]
   [0.4826789  0.5067582  0.6889693 ]
   [0.5624157  0.6462865  0.77867204]
   [0.56373215 0.4638537  0.7798768 ]
   [0.5474443  0.76229924 0.6768136 ]
   [0.56746906 0.34014055 0.81884205]
   [0.41343892 0.68149936 0.49731812]
   [0.44188008 0.37898666 0.71902007]
   [0.8731675  0.6248172  0.7297598 ]
   [0.87018764 0.48217773 0.7640122 ]
   [0.85125256 0.66556525 0.0973686 ]
   [0.84780216 0.3364153  0.14457896]
   [0.8798744  0.59491765 0.01380774]
   [0.8804672  0.5575608  0.03466001]]]]
[[[[0.49059588 0.5436859  0.5179992 ]
   [0.4696486  0.5625253  0.58182347]
   [0.46875152 0.52558404 0.7287581 ]
   [0.47905493 0.59157467 0.686149  ]
   [0.47611532 0.5044332  0.59643984]
   [0.55603456 0.6465153  0.76169753]
   [0.55876875 0.4566985  0.78692305]
   [0.5438184  0.7636106  0.82668847]
   [0.56097984 0.3312965  0.68120235]
   [0.409

[[[[0.39231572 0.524209   0.42200747]
   [0.37029296 0.5487809  0.740564  ]
   [0.36930507 0.50395286 0.64355695]
   [0.39079493 0.580761   0.7125963 ]
   [0.38945222 0.47511196 0.6940075 ]
   [0.49325728 0.6398517  0.7415075 ]
   [0.4866155  0.40741703 0.908834  ]
   [0.49072617 0.80246866 0.77103645]
   [0.49144793 0.2504861  0.6873505 ]
   [0.32836413 0.7209064  0.72886676]
   [0.32460183 0.318417   0.7976564 ]
   [0.8441241  0.6084301  0.75096625]
   [0.84928834 0.43569988 0.70364773]
   [0.8579566  0.6433802  0.057872  ]
   [0.8613086  0.21521692 0.15362081]
   [0.8745779  0.61354375 0.01202685]
   [0.8802831  0.44888186 0.01456675]]]]
[[[[0.37488875 0.5276671  0.5480151 ]
   [0.35590392 0.55222726 0.68340707]
   [0.3571806  0.5063456  0.66311276]
   [0.38838637 0.58210695 0.63751435]
   [0.3841791  0.48090097 0.686065  ]
   [0.48898038 0.64460593 0.8586945 ]
   [0.48651385 0.40965304 0.8871484 ]
   [0.48340017 0.8078672  0.68301785]
   [0.48596328 0.2542754  0.81356657]
   [0.315

[[[[0.3973026  0.52601695 0.659103  ]
   [0.37812814 0.5501044  0.7432425 ]
   [0.37920928 0.50388825 0.6276934 ]
   [0.4002751  0.58003145 0.57880014]
   [0.3986933  0.47111163 0.7676141 ]
   [0.5053648  0.64481664 0.89122975]
   [0.5001303  0.40497956 0.8911667 ]
   [0.53091407 0.8220326  0.7578443 ]
   [0.50480545 0.23763922 0.81722957]
   [0.3415845  0.8128051  0.68482155]
   [0.3222015  0.2337725  0.6947571 ]
   [0.8650545  0.6139904  0.7261743 ]
   [0.86514413 0.4342199  0.7503755 ]
   [0.8588432  0.63871336 0.0550063 ]
   [0.8609507  0.27775106 0.1104396 ]
   [0.8741207  0.62953883 0.01353422]
   [0.87766325 0.41673362 0.0071519 ]]]]
[[[[0.39969683 0.5241178  0.71771103]
   [0.37908098 0.5492711  0.77415776]
   [0.37931114 0.50302565 0.6257293 ]
   [0.39953083 0.57951546 0.5468238 ]
   [0.39635748 0.46922857 0.71552366]
   [0.5038357  0.64817363 0.91003394]
   [0.5000051  0.40050268 0.8736745 ]
   [0.5325414  0.82377446 0.85851943]
   [0.50867224 0.23569278 0.77465296]
   [0.345

[[[[0.40058336 0.5250055  0.6539192 ]
   [0.37912342 0.5471707  0.7622752 ]
   [0.38128316 0.50411654 0.6552652 ]
   [0.39611906 0.576298   0.7461746 ]
   [0.3956141  0.47288632 0.6554552 ]
   [0.49853778 0.6421306  0.7964692 ]
   [0.49369523 0.41530836 0.7913276 ]
   [0.50067437 0.8007213  0.79183817]
   [0.48010084 0.26184142 0.8234971 ]
   [0.3385832  0.7478832  0.62178665]
   [0.3187855  0.30431277 0.6491692 ]
   [0.8622792  0.6213502  0.75918245]
   [0.8620819  0.438858   0.76557887]
   [0.86172646 0.66056013 0.05795145]
   [0.8614614  0.27704152 0.19104981]
   [0.8775198  0.60708356 0.01634598]
   [0.88269776 0.45071834 0.02092117]]]]
[[[[0.40074968 0.5246109  0.6476113 ]
   [0.38001165 0.54635644 0.74746644]
   [0.38145027 0.50360596 0.663842  ]
   [0.3983124  0.5768659  0.8024942 ]
   [0.3995535  0.4724246  0.76133287]
   [0.503899   0.6481363  0.88763225]
   [0.49862152 0.41146693 0.86905813]
   [0.51032555 0.8142094  0.7724378 ]
   [0.48347673 0.25466985 0.76720834]
   [0.334

[[[[0.40691254 0.53057003 0.73988247]
   [0.38528562 0.55430347 0.80047023]
   [0.38765097 0.50930846 0.79206204]
   [0.4059689  0.58513    0.6615155 ]
   [0.40085632 0.48137078 0.636508  ]
   [0.49881387 0.6473907  0.7807448 ]
   [0.49448317 0.42764503 0.77874786]
   [0.4511753  0.77584493 0.7855611 ]
   [0.45957077 0.30249706 0.8421142 ]
   [0.32806826 0.6520183  0.567835  ]
   [0.31593698 0.40936622 0.6088324 ]
   [0.8584409  0.6238797  0.7990358 ]
   [0.85854596 0.44746315 0.82931983]
   [0.85869926 0.6612277  0.08468318]
   [0.8628571  0.29304036 0.14853352]
   [0.8796355  0.5815389  0.02385122]
   [0.87995934 0.52467823 0.07506281]]]]
[[[[0.40714276 0.532451   0.7201345 ]
   [0.38497686 0.5567107  0.7727804 ]
   [0.38751245 0.5108777  0.8176888 ]
   [0.40420586 0.5863044  0.6289662 ]
   [0.40013164 0.48145652 0.62991923]
   [0.4977494  0.64708185 0.78065383]
   [0.49466726 0.42566332 0.78990287]
   [0.45301753 0.7774445  0.6978651 ]
   [0.45997354 0.29604322 0.8425877 ]
   [0.328

[[[[0.40391546 0.51902467 0.6104066 ]
   [0.3817215  0.5410192  0.6120524 ]
   [0.38541198 0.50063634 0.767997  ]
   [0.39836952 0.57541573 0.7860408 ]
   [0.39935988 0.47682032 0.7145474 ]
   [0.4977897  0.64553875 0.78140265]
   [0.49652013 0.41658485 0.764297  ]
   [0.490084   0.79133195 0.7685658 ]
   [0.49292338 0.27941322 0.74986804]
   [0.33807707 0.6866603  0.7195884 ]
   [0.34422398 0.35563517 0.681907  ]
   [0.861777   0.6215481  0.79386455]
   [0.8628576  0.44105756 0.7804708 ]
   [0.8578021  0.6447742  0.05444556]
   [0.861103   0.27639225 0.16263467]
   [0.87191856 0.6275637  0.01537445]
   [0.8844337  0.47652173 0.01780444]]]]
[[[[0.40391546 0.51902467 0.6104066 ]
   [0.3817215  0.5410192  0.6120524 ]
   [0.38541198 0.50063634 0.767997  ]
   [0.39836952 0.57541573 0.7860408 ]
   [0.39935988 0.47682032 0.7145474 ]
   [0.4977897  0.64553875 0.78140265]
   [0.49652013 0.41658485 0.764297  ]
   [0.490084   0.79133195 0.7685658 ]
   [0.49292338 0.27941322 0.74986804]
   [0.338

[[[[0.3861733  0.5589663  0.69722503]
   [0.35857797 0.58008397 0.61620533]
   [0.36564642 0.53609097 0.77032095]
   [0.3698694  0.6219851  0.6798111 ]
   [0.3822505  0.5179789  0.7842295 ]
   [0.50539863 0.7062153  0.85652596]
   [0.5053183  0.4588129  0.84877634]
   [0.6820941  0.7951612  0.6162554 ]
   [0.6743028  0.4032994  0.75460696]
   [0.8462042  0.8279958  0.45721138]
   [0.8386352  0.35943896 0.67357415]
   [0.8645219  0.65123725 0.5876547 ]
   [0.8631884  0.47047037 0.67126024]
   [0.99719703 0.82097805 0.03074703]
   [0.8760366  0.34453833 0.03032935]
   [0.9882943  0.8215524  0.04584756]
   [0.8802971  0.4830398  0.02093205]]]]
[[[[0.3730913  0.5715773  0.5023657 ]
   [0.34635514 0.5906504  0.7624384 ]
   [0.35558623 0.54434764 0.49301773]
   [0.36273023 0.63544655 0.76535845]
   [0.37851018 0.5299326  0.7874832 ]
   [0.5017394  0.7272562  0.83970225]
   [0.5033794  0.4695387  0.904118  ]
   [0.699274   0.77572197 0.7013548 ]
   [0.6766064  0.4174504  0.69931036]
   [0.870

[[[[0.19965392 0.61656606 0.77556515]
   [0.16510034 0.6477158  0.59437394]
   [0.17102703 0.5851476  0.59091187]
   [0.19182138 0.69834244 0.6609785 ]
   [0.20781961 0.5463892  0.6619377 ]
   [0.3591689  0.8125896  0.8347819 ]
   [0.38041374 0.46696958 0.91792214]
   [0.5963538  0.93768525 0.8026899 ]
   [0.64634985 0.3642016  0.82473826]
   [0.35414398 0.72322583 0.6877194 ]
   [0.8600056  0.28443414 0.34058517]
   [0.8414273  0.779423   0.5058139 ]
   [0.8420458  0.5170377  0.6469378 ]
   [0.8435222  0.8221586  0.01934469]
   [0.8685352  0.31789073 0.01712027]
   [0.8611359  0.7007145  0.00781468]
   [0.8799564  0.61029255 0.00726792]]]]
[[[[0.18041033 0.6679856  0.33288664]
   [0.15049958 0.6693074  0.4400726 ]
   [0.15251517 0.63006896 0.35478437]
   [0.15958647 0.74576247 0.25408882]
   [0.17546445 0.5871435  0.44779342]
   [0.34840143 0.8707148  0.50858474]
   [0.3707896  0.49184024 0.8508812 ]
   [0.5835688  0.9837407  0.3563498 ]
   [0.64113414 0.40395114 0.68403196]
   [0.372

[[[[0.27308184 0.09622566 0.39668632]
   [0.23830146 0.140065   0.48998806]
   [0.22629105 0.05753225 0.43616837]
   [0.26279822 0.17886911 0.52838594]
   [0.2369701  0.01347802 0.22773919]
   [0.49600458 0.15827894 0.54962164]
   [0.4583227  0.00711887 0.09494936]
   [0.74832714 0.1390417  0.39709824]
   [0.7712605  0.01911375 0.16206655]
   [0.8882067  0.13190955 0.09324858]
   [0.531958   0.05485552 0.01816204]
   [0.88882256 0.08283981 0.17236146]
   [0.8774997  0.00789601 0.10968649]
   [0.69735235 0.02244497 0.03335568]
   [0.6949327  0.0048866  0.02487051]
   [0.6131973  0.03068302 0.03498355]
   [0.8719146  0.01113963 0.02341539]]]]
[[[[0.2512058  0.1416272  0.37110907]
   [0.2020847  0.19429049 0.5861877 ]
   [0.19282696 0.09564104 0.46462402]
   [0.24119538 0.23155773 0.4682098 ]
   [0.20324099 0.02153101 0.2846573 ]
   [0.48119807 0.2236999  0.45613313]
   [0.43604875 0.00878914 0.10411432]
   [0.7931499  0.22431087 0.19377694]
   [0.7127857  0.02289646 0.0516147 ]
   [0.577

[[[[0.5147186  0.4925587  0.71982926]
   [0.42037153 0.5504505  0.6923722 ]
   [0.42189807 0.42349696 0.5939118 ]
   [0.38393813 0.60962975 0.6383415 ]
   [0.39005888 0.327538   0.674166  ]
   [0.48262617 0.6558984  0.5613096 ]
   [0.55608517 0.17032966 0.8008017 ]
   [0.7935076  0.7509545  0.3857416 ]
   [0.9526373  0.02738792 0.04362449]
   [0.80084634 0.7670977  0.02427268]
   [0.85962915 0.3139105  0.00917482]
   [0.56278527 0.5275411  0.09153014]
   [0.9052791  0.22492844 0.03002602]
   [0.6661639  0.8884482  0.0548526 ]
   [0.5598501  0.15517764 0.0239217 ]
   [0.8769027  0.7949514  0.00944614]
   [0.85580987 0.29499573 0.00262856]]]]
[[[[0.5161927  0.49101815 0.75193954]
   [0.43065524 0.545869   0.63392407]
   [0.43002242 0.42639017 0.7372988 ]
   [0.39371476 0.6094398  0.54648924]
   [0.40659577 0.33014002 0.63184893]
   [0.48523003 0.6535984  0.76565266]
   [0.54789776 0.18848401 0.750937  ]
   [0.79720944 0.75162625 0.5068721 ]
   [0.86187476 0.06332184 0.09352344]
   [0.852

[[[[0.46856257 0.40900227 0.6810998 ]
   [0.36416957 0.47182    0.7581264 ]
   [0.37626207 0.33164918 0.46663752]
   [0.3306734  0.54997766 0.6104748 ]
   [0.36093563 0.24586278 0.6531036 ]
   [0.4194504  0.60868365 0.7286802 ]
   [0.56481063 0.12021282 0.7577016 ]
   [0.77667713 0.7371959  0.4155599 ]
   [0.86574376 0.04254173 0.12137291]
   [0.8955239  0.8370065  0.05404252]
   [0.87198466 0.18676516 0.02419904]
   [0.8443565  0.49395877 0.1761038 ]
   [0.8710336  0.24926494 0.24152127]
   [0.84356403 0.59102786 0.01259887]
   [0.84561527 0.16803698 0.04748619]
   [1.0000985  0.6725179  0.01046062]
   [0.86026716 0.23364095 0.02515221]]]]
[[[[0.46202263 0.42310923 0.51986414]
   [0.35090387 0.48357373 0.62382525]
   [0.3690247  0.34158    0.7412401 ]
   [0.32137594 0.5553484  0.7390209 ]
   [0.3583393  0.24965557 0.66832846]
   [0.41398618 0.6167241  0.61303705]
   [0.56974566 0.11675516 0.6349586 ]
   [0.7562834  0.73109436 0.5741029 ]
   [0.8685323  0.02630166 0.16182381]
   [0.890

[[[[0.47006476 0.46111286 0.5980008 ]
   [0.36361885 0.5199125  0.7445986 ]
   [0.37685394 0.37213907 0.5672973 ]
   [0.31159097 0.57953274 0.57044894]
   [0.3380397  0.25542492 0.6553855 ]
   [0.41726062 0.6375488  0.71567833]
   [0.5781558  0.12859836 0.60118353]
   [0.7579829  0.74643034 0.5310313 ]
   [0.89511794 0.02336373 0.04132944]
   [0.89157796 0.89054674 0.07533756]
   [0.8711002  0.2306641  0.0113048 ]
   [0.84104514 0.51934624 0.1419712 ]
   [0.88152283 0.2541867  0.07535899]
   [0.83536434 0.72433347 0.00498861]
   [0.84154224 0.17760943 0.02956024]
   [0.8993882  0.8541604  0.00895643]
   [0.8502406  0.19728857 0.01755843]]]]
[[[[0.46915206 0.48527598 0.6592726 ]
   [0.36395842 0.5386193  0.81474614]
   [0.3802914  0.39970264 0.43324587]
   [0.30925685 0.58767563 0.57808214]
   [0.34369895 0.2734532  0.675268  ]
   [0.42261013 0.64385164 0.73039913]
   [0.5760695  0.14019099 0.55402327]
   [0.7653417  0.7597508  0.38476202]
   [0.89574504 0.02715076 0.04983127]
   [0.893

In [28]:
frame.shape

(480, 640, 3)

In [14]:
keypoints_with_scores

array([[[[0.44873852, 0.5339416 , 0.7542602 ],
         [0.39594394, 0.5788866 , 0.4924848 ],
         [0.40024984, 0.4929952 , 0.50635546],
         [0.3926404 , 0.6258533 , 0.5367822 ],
         [0.39611194, 0.4284733 , 0.58908904],
         [0.566757  , 0.6846082 , 0.5233538 ],
         [0.5346632 , 0.32161275, 0.7171906 ],
         [0.8484737 , 0.6775893 , 0.42011315],
         [0.8227345 , 0.21542153, 0.68319607],
         [0.6088667 , 0.75909346, 0.388299  ],
         [0.8669281 , 0.38694745, 0.03524938],
         [0.9113476 , 0.5400338 , 0.081559  ],
         [0.8968129 , 0.32546002, 0.11971   ],
         [0.87023604, 0.6863851 , 0.00916269],
         [0.81712073, 0.2702737 , 0.01690695],
         [1.0257709 , 0.6813783 , 0.00661919],
         [1.0117491 , 0.39638937, 0.00217554]]]], dtype=float32)

In [27]:
np.squeeze(keypoints_with_scores)

array([[0.44873852, 0.5339416 , 0.7542602 ],
       [0.39594394, 0.5788866 , 0.4924848 ],
       [0.40024984, 0.4929952 , 0.50635546],
       [0.3926404 , 0.6258533 , 0.5367822 ],
       [0.39611194, 0.4284733 , 0.58908904],
       [0.566757  , 0.6846082 , 0.5233538 ],
       [0.5346632 , 0.32161275, 0.7171906 ],
       [0.8484737 , 0.6775893 , 0.42011315],
       [0.8227345 , 0.21542153, 0.68319607],
       [0.6088667 , 0.75909346, 0.388299  ],
       [0.8669281 , 0.38694745, 0.03524938],
       [0.9113476 , 0.5400338 , 0.081559  ],
       [0.8968129 , 0.32546002, 0.11971   ],
       [0.87023604, 0.6863851 , 0.00916269],
       [0.81712073, 0.2702737 , 0.01690695],
       [1.0257709 , 0.6813783 , 0.00661919],
       [1.0117491 , 0.39638937, 0.00217554]], dtype=float32)

In [7]:
keypoints_with_scores.shape

(1, 1, 17, 3)

In [25]:
left_shoulder = keypoints_with_scores[0][0][5]
left_wrist = keypoints_with_scores[0][0][9]
print('Height(Y-axis) & Width(X-axis) of Left Shoulder:',left_shoulder[:2],'\nHeight(Y-axis) & Width(X-axis) of Left Wrist:',left_wrist[:2]) # Height & Width
print('Confidence Interval of Left Shoulder:',left_shoulder[2],'\nConfidence Interval of Left Wrist:',left_wrist[2]) # Confidence Interval or Accuracy

Height(Y-axis) & Width(X-axis) of Left Shoulder: [0.566757  0.6846082] 
Height(Y-axis) & Width(X-axis) of Left Wrist: [0.6088667  0.75909346]
Confidence Interval of Left Shoulder: 0.5233538 
Confidence Interval of Left Wrist: 0.388299


In [30]:
print('Actual Coordinates of Left Shoulder:',np.array(left_shoulder[:2]*[480,640]).astype(int))
print('Actual Coordinates of Left Wrist:',np.array(left_wrist[:2]*[480,640]).astype(int))

Actual Coordinates of Left Shoulder: [272 438]
Actual Coordinates of Left Wrist: [292 485]
